CREATE TABLE image
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR(255),
    file_tye     VARCHAR(255),
    image        OID,
    download_url VARCHAR(255),
    recipe_id    BIGINT,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE recipe
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255),
    instruction      VARCHAR(255),
    prep_time        VARCHAR(255),
    cook_time        VARCHAR(255),
    category         VARCHAR(255),
    description      VARCHAR(255),
    cuisine          VARCHAR(255),
    like_count       INTEGER                                 NOT NULL,
    average_rating   DOUBLE PRECISION                        NOT NULL,
    total_rate_count INTEGER                                 NOT NULL,
    user_id          BIGINT,
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);

CREATE TABLE recipe_ingredients
(
    recipe_id  BIGINT NOT NULL,
    ingredient VARCHAR(255)
);

CREATE TABLE review
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stars     INTEGER                                 NOT NULL,
    feed_back VARCHAR(255),
    user_id   BIGINT,
    recipe_id BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE image
    ADD CONSTRAINT uc_image_recipe UNIQUE (recipe_id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipe (id);

ALTER TABLE recipe
    ADD CONSTRAINT FK_RECIPE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipe (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE recipe_ingredients
    ADD CONSTRAINT fk_recipe_ingredients_on_recipe FOREIGN KEY (recipe_id) REFERENCES recipe (id);

CREATE TABLE public.likes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipe_id BIGINT,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

ALTER TABLE public.likes
    ADD CONSTRAINT FK_LIKES_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipe (id);